### ISSUE TITLE
Release version crashes exporting to GPX and files are corrupted

### ISSUE THREAD

**Issue by teknologika** [velocitek/speedtrack#5] opened 2016-02-01 04:01 UTC
The 1.0 version available from the website does not download all the data points and crashes when exporting to gpx.

Steps to repo.

1. Go for a sail with a speed puck
2. Download 1.0 of Velocitool
3. Use El Capitan 10.11.3

<img width="641" alt="screen shot 2016-02-01 at 2 53 59 pm 1" src="https://cloud.githubusercontent.com/assets/211376/12708452/b0039270-c8f3-11e5-9932-496eaf0b2174.png">

4. Download track, note that some of the data points are missed.
5. Try and export ... export crashed, and file is corrupted.

<img width="565" alt="screen shot 2016-02-01 at 2 52 08 pm" src="https://cloud.githubusercontent.com/assets/211376/12708454/b4e9ced0-c8f3-11e5-8606-5b05f33f92f9.png">

6. Build from source and run.
7. Download track again, note data points total matches.

<img width="563" alt="screen shot 2016-02-01 at 2 53 19 pm" src="https://cloud.githubusercontent.com/assets/211376/12708453/b2c803ba-c8f3-11e5-8874-49c7401452eb.png">

Tracks attached. 

[Tracks.zip](https://github.com/velocitek/speedtrack/files/111707/Tracks.zip)

**Comment by e-noyau** [comment] 2016-02-01 08:47
Thanks for the report.

Yes, the version on the site doesn't work with El Capitan at all. The issue you see is because the library used by 1.0 to get the data from the device is returning incorrect data in 10.11. An update to the latest release fix this issue.

This change of library triggered some other changes, and the team at Velocitek is currently making sure nothing was broken in the process. They will push the automatic update to 1.1 soon.

I'm closing this issue, as it is no longer a code problem, the issue is fixed, just not released yet.

**Closed** 2016-02-13 01:24 UTC
